### PR TITLE
Pin 3D camera zoom between min and max values

### PR DESCRIPTION
**Pull request by Carifio24**
This PR pins the zoom range (in 3D mode only) to prevent a user from zooming to far in or out. @patudom the min and max zoom ranges are set in the component data; feel free to change them.

### CODE REVIEW

**Comment by johnarban** [comment]
So this has the same issue as I had in trying to implement this with `gotoRADecZoom` in that it bounces at the limits because it overshoots and then bounces back to the pinned value. I hadn't been able to find a way around this, but was gonna try to look

**Comment by patudom** [comment]
Adding that on mobile (where the zoom is really an issue), you can zoom all the way to the solar system with one pinch, so even though this bounces you back to the specified range, it's still a weird/confusing experience.

@johnarban suggested that we could avoid this problem by specifying limits directly within WWT instead of watching for it. @Carifio24, do you know if this is already possible, and if not, how hard would it be to implement?

Screen Shot 2024-01-05 at 12 28 31 PM

**Comment by Carifio24** [comment]
Turns out this can indeed be done in WWT directly (and it's even exposed at the Typescript level, not sure how I missed that). I've updated the implementation to use that method instead.

I haven't tested this yet due to bad plane wifi not wanting to load WWT assets, but feel free to merge if it looks good, otherwise I can take another look later.

**Comment by johnarban** [comment]
I have added a patch to fix an issue with the minimum zoom not working. there is a PR on https://github.com/WorldWideTelescope/wwt-webgl-engine/pull/292 to fix it at the source as well

**Comment by johnarban** [comment]
This works w/ @Carifio24's overriding the builtin zoom function. Tested in both 2D & 3D

**Pull request merged**
