### PR TITLE
Add Map Quiz

### PR DESCRIPTION
**Pull request by johnarban**
This adds in the map quiz. Built off of `mc-radiogroup` from hubbleds, when a selection is made it emits a `select` event with `{index: number, correct: boolean, neutral: boolearn, tries: boolearn}`. It turns off the ability to select once the correct answer is given. you can limit the number of tries by setting a `max-tries` prop.

### CODE REVIEW

**Comment by Carifio24** [comment]
The MC component is pretty generic - feels to me like we'd want to have that in `common`.

**Comment by patudom** [comment]
I like this a lot! Thanks so much, @johnarban!! I pushed a commit that adds some styling that should look like this:

Screen Shot 2023-10-03 at 9 47 48 PM

Screen Shot 2023-10-03 at 9 42 26 PM

I think we want the most recently flipped card to have a white border, but I couldn't figure out what was active and what was focused.

Also, if I click the correct answer too many times, it reverts back to the old mc-radiogroup styling. Not sure why it does that, but we should fix if possible.
Screen Shot 2023-10-03 at 9 41 57 PM

**Comment by johnarban** [comment]
Last five commits fix the bugs you mentiond. Also, while focus state for the border, I recommend not setting it and letting the brower handle it. For the image-label component, the `active` state is when the mouse is pressed down. To set the `activeBorder` you would either pass it a string `"1px solid red"` or use it like a javascript directive with <code>:activeBorder="&#96;1px solid ${color}&#96;" </code>, and use `@`. The component doesn't currently emit when it is in the `active` or `hover` or `focus` state, but perhaps it should?

**Comment by patudom** [comment]
This looks good, @johnarban. Good call on adding the long form of the responses. I updated the descriptions to have a parallel format because I think that will make it easier for the user to identify how they differ from each other. I also added those same path descriptions to the alt text for the map image and gave the eclipse schematic a more detailed alt text.  I also bumped up the font size on the answer text because I'm not connected to my desktop monitor right now and the fonts were unreadable on my computer. Hopefully they will still fit.

If the changes I made look ok to you and @Carifio24, I'm ready for this to be merged.

**Comment by johnarban** [comment]
Those changes look good to me.

**Pull request merged**
