### PR TITLE
Initial location selector view

### LINKED ISSUE #191: Change default map center and zoom level for eclipse mini
- [x] For the Eclipse Mini, please update the defaults so that both maps start with this lat/long and zoom level:

`setView([38, -97], 2.5)`

The map should look like so:
Screen Shot 2023-09-21 at 6 15 38 PM

I also had to change the map css:
```   
      #map-container-map {
            height: 230px;
            width: 350px;
            ...
```

- [ ] If possible, can we shorten the map attribution (especially for the watercolor map) and make the full attribution a hover-over or something?

### PR DESCRIPTION
**Pull request by Carifio24**
This PR partially resolves #191 by adding options to the location selector to allow setting the initial view location and zoom, and then using these in the eclipse mini.

Since a Leaflet map's `zoomDelta` is 1 by default, I felt it made more sense to put the zoom as 3 instead of 2.5. (Alternatively, we could change the `zoomDelta` for the eclipse mini)

### CODE REVIEW

**Comment by Carifio24** [comment]
@patudom This PR does require rebuilding `common` if you haven't done that.

If you have, not sure off the top of my head. Will try a fresh build and see if I can reproduce.

**Comment by patudom** [comment]
I did rebuild common twice. I can try again.

**Comment by johnarban** [comment]
It is working ok for me

**Comment by Carifio24** [comment]
The latest commit should fix this issue - let me know if you still see it.

**Comment by patudom** [comment]
Ok, the issue went away on load, but then when I tried to switch map modes from Explore to Choose, I got:

**Pull request merged**
