### PR TITLE
Add template and script for generating new minis

### LINKED ISSUE #138: Make a template for all minis going forward
- [ ] Create a Mini template based on how we want the standardized look to be going forward
- [ ] Implement a command line method in the package.json file to automatically create the skeleton setup for new Minis

### LINKED ISSUE #157: Add "draft" flag to unfinished mini stories so they don't build
Instead of merging lots of PRs to a dev branch while a new mini is in development, let's set this repo up so that any folder with a "draft" flag does not get built. This way we can merge new PRs to main without getting a dev branch wildly out of sync from main.

When a story is ready to deploy, we can remove the "draft" flag.

- [x] Set up template so all new stories have the draft flag.
- [x] Add draft flag to all unfinished stories (RadWave & AnnularEclipse)

### PR DESCRIPTION
**Pull request by Carifio24**
This PR resolves #138. To do this, it adds a `template` folder which contains a basic implementation of a mini that can be used to generate new minis, along with a script `create-mini.sh` which will do just that.

The relevant commands have been added a the top-level `create` script, so you can run e.g.

`yarn create-mini <workspace>`

This will do the following:
- Add a workspace named `<workspace>` in `package.json`
- Create a folder `<workspace>`. The contents of this folder will match those in `template`, but with relevant items replaced with the workspace name throughout (the component file will be PascalCase - so if your workspace is `my-mini`, the main component file will be `MyMini.vue`.

I've marked this as a draft for now as it depends heavily on some bash utilities - in particular `sed` and `jq`. `sed` should be present on macOS but apparently has some differences, I need to test this out and make sure that they don't pop up here. `jq` should be installable via `brew`, but I'll probably move the JSON manipulation over to a Node script or something.

Feel free to try this out and give any suggestions on the template content.

Edit: Note that merging this will (together with the individual mini PRs) resolve #157.

### CODE REVIEW

**Comment by Carifio24** [comment]
I've replaced the `jq` part of the script with a small Node script to make this easier. Still need to test out the `sed` commands on macOS, but otherwise I think this is ready to go.

**Comment by patudom** [comment]
I think the default should be that the text in the browser tab is initialized as the name of the Mini.

Screen Shot 2023-08-28 at 3 58 03 PM

**Comment by patudom** [comment]
Since the generated .vue file is so long (>600 lines), it would be helpful if put in commented out section dividers that indicate in a very easy-to-see way what is in each part of the file. For example, something like:

```
<!-- This contains the video that is displayed when the video icon is clicked. -->

<!-- This contains the informational content that is displayed when the book icon is clicked. -->
```

and similar groupings in the `script` and `style` sections

**Comment by patudom** [comment]
We should also include the bottom content with all the different project icons by default.

**Comment by Carifio24** [comment]
@patudom I think I've made all the requested changes here. If you want to modify the comments at all, feel free to do so in `MainComponent.vue` (which will be the content of the generated mini)

**Comment by patudom** [comment]
Thanks, @Carifio24, this looks great. One tiny request - is it possible to add spaces to the title of the Mini that appears in the browser tabs (instead of Pascal case)?

**Comment by Carifio24** [comment]
@patudom Just tweaked it to add spaces to the page title

**Pull request merged**
